In [4]:
conda install numpy

Channels:
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: c:\Users\user\anaconda3\envs\midproject

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    mkl-service-2.4.0          |  py313h827c3e9_2          64 KB
    mkl_fft-1.3.11             |  py313h827c3e9_0         172 KB
    mkl_random-1.2.8           |  py313hce38976_0         252 KB
    numpy-2.2.5                |  py313ha127e54_0          14 KB
    numpy-base-2.2.5           |  py313haaa8b43_0         7.3 MB
    setuptools-72.1.0          |  py313haa95532_0         2.6 MB
    ------------------------------------------------------------
                                           Total:        10.3 MB

The following NEW packages will be INSTALLED:

  blas               pkgs/main/win-64::blas-1.0-mkl
  intel-openmp       pkgs/main/win-64::intel-openmp-2023.1.0-h59b6b97_46320
  mkl                pkgs/main/win-64::mkl-2023.1.0-h6b88ed4_46358
  mkl-service        pkgs/main/win-64::mkl-service-2.4.0-py313h827c3e9_2
  mkl_fft            pkgs/main/win-64::mkl_fft-1.3.11-py313h827c3e9_0
  mkl_random         pkgs/main/win-64::mkl_random-1.2.8-py313hce38976_0
  numpy              pkgs/main/win-64::numpy-2.2.5-py313ha127e54_0
  numpy-base         pkgs/main/win-64::numpy-base-2.2.5-py313haaa8b43_0
  tbb                pkgs/main/win-64::tbb-2021.8.0-h59b6b97_0

The following packages will be DOWNGRADED:

  setuptools                         78.1.1-py313haa95532_0 --> 72.1.0-py313haa95532_0



Downloading and Extracting Packages: ...working...
numpy-base-2.2.5     | 7.3 MB    |            |   0%

setuptools-72.1.0    | 2.6 MB    |            |   0%


mkl_random-1.2.8     | 252 KB    |            |   0%



mkl_fft-1.3.11       | 172 KB    |            |   0%




mkl-service-2.4.0    | 64 KB     |            |   0%





numpy-2.2.5          | 14 KB     |            |   0%



mkl_fft-1.3.11       | 172 KB    | ########## | 100%




mkl-service-2.4.0    | 64 KB     | ########## | 100%


mkl_random-1.2.8     | 252 KB    | ########## | 100%
numpy-base-2.2.5     | 7.3 MB    | ##6        |  26%

setuptools-72.1.0    | 2.6 MB    | 1          |   2%





numpy-2.2.5          | 14 KB     | ########## | 100%




mkl-service-2.4.0    | 64 KB     | ########## | 100%




mkl-service-2.4.0    | 64 KB     | ########## | 100%


mkl_random-1.2.8     | 252 KB    | ########## | 100%


mkl_random-1.2.8     | 252 KB    | ########## | 100%





numpy-2.2.5          | 14 KB     | ########## | 100%





numpy-2.2.5          | 14 KB     | ########## | 100%



mkl_fft-1.3.11       | 172 KB    | ########## | 100%



mkl_fft-1.3.11       | 172 KB    | ########## | 100%
numpy-base-2.2.5     | 7.3 MB    | #######8   |  78%

setuptools-72.1.0    | 2.6 MB    | ######4    |  64%
numpy-base-2.2.5     | 7.3 MB    | ########## | 100%

setuptools-72.1.0    | 2.6 MB    | ########## | 100%

setuptools-72.1.0    | 2.6 MB    | ########## | 100%

setuptools-72.1.0    | 2.6 MB    | ########## | 100%
numpy-base-2.2.5     | 7.3 MB    | ########## | 100%





















                                                      done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

Note: you may need to restart the kernel to use updated packages.

In [6]:
conda install pandas

Channels:
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: c:\Users\user\anaconda3\envs\midproject

  added / updated specs:
    - pandas


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bottleneck-1.4.2           |  py313h2cb717b_0         145 KB
    numexpr-2.10.1             |  py313h4cd664f_0         186 KB
    pandas-2.2.3               |  py313h5da7b33_0        14.3 MB
    python-dateutil-2.9.0post0 |  py313haa95532_2         307 KB
    python-tzdata-2025.2       |     pyhd3eb1b0_0         141 KB
    pytz-2024.1                |  py313haa95532_0         202 KB
    six-1.17.0                 |  py313haa95532_0          38 KB
    ------------------------------------------------------------
                                           Total:        15.3 MB

The following NEW packages will be INSTALLED:

  bottleneck         pkgs/main/win-64::bottleneck-1.4.2-py313h2cb717b_0
  numexpr            pkgs/main/win-64::numexpr-2.10.1-py313h4cd664f_0
  pandas             pkgs/main/win-64::pandas-2.2.3-py313h5da7b33_0
  python-dateutil    pkgs/main/win-64::python-dateutil-2.9.0post0-py313haa95532_2
  python-tzdata      pkgs/main/noarch::python-tzdata-2025.2-pyhd3eb1b0_0
  pytz               pkgs/main/win-64::pytz-2024.1-py313haa95532_0
  six                pkgs/main/win-64::six-1.17.0-py313haa95532_0



Downloading and Extracting Packages: ...working...
pandas-2.2.3         | 14.3 MB   |            |   0%

python-dateutil-2.9. | 307 KB    |            |   0%


pytz-2024.1          | 202 KB    |            |   0%



numexpr-2.10.1       | 186 KB    |            |   0%




bottleneck-1.4.2     | 145 KB    |            |   0%





python-tzdata-2025.2 | 141 KB    |            |   0%






six-1.17.0           | 38 KB     |            |   0%




bottleneck-1.4.2     | 145 KB    | ########## | 100%


pytz-2024.1          | 202 KB    | ########## | 100%



numexpr-2.10.1       | 186 KB    | ########## | 100%
pandas-2.2.3         | 14.3 MB   | 5          |   6%





python-tzdata-2025.2 | 141 KB    | ########## | 100%

python-dateutil-2.9. | 307 KB    | ########## | 100%






six-1.17.0           | 38 KB     | ########## | 100%
pandas-2.2.3         | 14.3 MB   | ####       |  40%



numexpr-2.10.1       | 186 KB    | ########## | 100%



numexpr-2.10.1       | 186 KB    | ########## | 100%
pandas-2.2.3         | 14.3 MB   | #######7   |  78%




bottleneck-1.4.2     | 145 KB    | ########## | 100%




bottleneck-1.4.2     | 145 KB    | ########## | 100%
pandas-2.2.3         | 14.3 MB   | ########## | 100%

python-dateutil-2.9. | 307 KB    | ########## | 100%

python-dateutil-2.9. | 307 KB    | ########## | 100%






six-1.17.0           | 38 KB     | ########## | 100%






six-1.17.0           | 38 KB     | ########## | 100%


pytz-2024.1          | 202 KB    | ########## | 100%


pytz-2024.1          | 202 KB    | ########## | 100%





python-tzdata-2025.2 | 141 KB    | ########## | 100%





python-tzdata-2025.2 | 141 KB    | ########## | 100%
pandas-2.2.3         | 14.3 MB   | ########## | 100%




























                                                      done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

Note: you may need to restart the kernel to use updated packages.

In [10]:
conda install openpyxl

Channels:
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: c:\Users\user\anaconda3\envs\midproject

  added / updated specs:
    - openpyxl


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    et_xmlfile-1.1.0           |  py313haa95532_1          13 KB
    openpyxl-3.1.5             |  py313h827c3e9_1         666 KB
    ------------------------------------------------------------
                                           Total:         679 KB

The following NEW packages will be INSTALLED:

  et_xmlfile         pkgs/main/win-64::et_xmlfile-1.1.0-py313haa95532_1
  openpyxl           pkgs/main/win-64::openpyxl-3.1.5-py313h827c3e9_1



Downloading and Extracting Packages: ...working...
openpyxl-3.1.5       | 666 KB    |            |   0%

et_xmlfile-1.1.0     | 13 KB     |            |   0%

et_xmlfile-1.1.0     | 13 KB     | ########## | 100%
openpyxl-3.1.5       | 666 KB    | ########## | 100%

et_xmlfile-1.1.0     | 13 KB     | ########## | 100%
openpyxl-3.1.5       | 666 KB    | ########## | 100%
openpyxl-3.1.5       | 666 KB    | ########## | 100%



                                                      done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

Note: you may need to restart the kernel to use updated packages.

In [17]:
import numpy as np
import pandas as pd
import openpyxl
from IPython.display import display, HTML

In [22]:
df1 = pd.read_excel('data\시도별_1인당_지역내총생산__지역총소득__개인소득_20250528134501.xlsx', engine='openpyxl')
df1.columns = [col.replace(' p)', '') for col in df1.columns]
display(HTML(df1.to_html(index=False)))

c:\Users\user\anaconda3\envs\midproject\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [24]:
df2 = df1[['시도별','2020','2021','2022']]
df2 = df2.iloc[1:]
df2

        시도별   2020   2021   2022
1        전국  37515  40271  41948
2     서울특별시  46221  49680  51612
3     부산광역시  27204  29395  31611
4     대구광역시  23910  25543  26736
5     인천광역시  30367  33551  35295
6     광주광역시  28433  29779  30900
7     대전광역시  29757  31590  33682
8     울산광역시  60895  69392  77511
9   세종특별자치시  36473  38157  37875
10      경기도  36521  38879  39969
11      강원도  32026  33679  34426
12     충청북도  42667  46123  48616
13     충청남도  53078  57622  58937
14     전라북도  29252  31187  32464
15     전라남도  43957  49572  51422
16     경상북도  39887  42896  43886
17     경상남도  33186  34046  36501
18  제주특별자치도  29334  29988  31150

In [26]:
# 수도권 지역 리스트 정의
capital_region = ['서울특별시', '인천광역시', '경기도']

# 새로운 열 '지역구분' 추가
df2['지역구분'] = df2['시도별'].apply(lambda x: '수도권' if x in capital_region else '비수도권')
df2

        시도별   2020   2021   2022  지역구분
1        전국  37515  40271  41948  비수도권
2     서울특별시  46221  49680  51612   수도권
3     부산광역시  27204  29395  31611  비수도권
4     대구광역시  23910  25543  26736  비수도권
5     인천광역시  30367  33551  35295   수도권
6     광주광역시  28433  29779  30900  비수도권
7     대전광역시  29757  31590  33682  비수도권
8     울산광역시  60895  69392  77511  비수도권
9   세종특별자치시  36473  38157  37875  비수도권
10      경기도  36521  38879  39969   수도권
11      강원도  32026  33679  34426  비수도권
12     충청북도  42667  46123  48616  비수도권
13     충청남도  53078  57622  58937  비수도권
14     전라북도  29252  31187  32464  비수도권
15     전라남도  43957  49572  51422  비수도권
16     경상북도  39887  42896  43886  비수도권
17     경상남도  33186  34046  36501  비수도권
18  제주특별자치도  29334  29988  31150  비수도권

In [33]:
df_grouped=df2.groupby('지역구분')[['2020', '2021', '2022']].mean()
df_grouped.to_excel('GRDP.xlsx', index=True)